### ISSUE TITLE
Error uploading IGC file from XCTrack

### ISSUE THREAD

**Issue by skeff** [dbrgn/flugbuech#27]
I tried uploading an IGC file created with XCTrack, but I get the following error:
> Could not process IGC file: Error: Error parsing lines: SyntaxError

IGC file attached.

[XCTrack_IGC.zip](https://github.com/dbrgn/flugbuech/files/3965051/XCTrack_IGC.zip)

**Comment by dbrgn** [comment]
Thanks for the IGC file! The parser is unhappy about this line:

    I023636LAD3737LOD

Strictly speaking, the record is not positioned in a valid way, since it follows an `L` record while the spec states:

![irecord](https://user-images.githubusercontent.com/105168/70931968-ea564080-2038-11ea-81b9-debd299226de.png)

However, that shouldn't really be an issue.

The record itself looks well-formed:

```
I          # I extension record
02         # Two extensions will follow
36 36 LAD  # Extension one: LAD
37 37 LOD  # Extension two: LOD
```

I'll check out the IGC parsing library to see if there's a bug.

**Comment by dbrgn** [comment]
Haha, the reason was different :smile: The file contains windows line endings, and all previous record types end with an arbitrary string, the `I` record is the first one that's not valid with a trailing newline.

I'll provide a fix soon.

**Comment by dbrgn** [comment]
Should be fixed, the new version is now live! Thanks for the report, @skeff.
